### ISSUE TITLE
Seems not to work with 1.15

### ISSUE THREAD

**Issue by Velkow** [Alan-Gomes/mcspring-boot#20]
Hey, I have an error running with amazon-corretto-11 and minecraft server 1.15, maybe this does not work with this version.

```
[23:40:58] [Server thread/ERROR]: Could not load 'plugins/Speakeasy-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/springframework/core/io/ResourceLoader
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:349) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:268) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/io/ResourceLoader
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.io.ResourceLoader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-fc24934]
        ... 6 more
```

Best regards,
Velkow

**Comment by ignissak** [comment]
It does. You didn't compile dependencies with your .jar.
